config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'genres/index'

  get 'genres/show'

  get '/thankyou', to: 'pages#thanks'
  
  resources :artists
  get 'dashboards/show'

  resources :thanks, only: :show
  devise_for :users, controllers: {:registrations => 'users/registrations'}
  resources :songs
  resources :genres
  get 'pages/index'

  get 'thankyou/:id', to: "thanks#show"

  get 'pages/contact'

  get :search, controller: :searches


  get "/dashboard", to: "dashboards#show"
  root "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    # has_many :songs, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :genre

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  has_attached_file :mp3
  validates_attachment :mp3,content_type: { content_type: ["audio/mpeg", "audio/mp3"] },
                      file_name: { matches: [/mp3\Z/] }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_action :set_artist, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin!, except: [:show]
	# GET /artists
	# GET /artists.json
	def index
		@artists = Artist.all
	end

	# GET /artists/1
	# GET /artists/1.json
	def show
	end

	# GET /artists/new
	def new
		@artist = Artist.new
	end

	# GET /artists/1/edit
	def edit
	end

	# POST /artists
	# POST /artists.json
	def create
		@artist = Artist.new(artist_params)

		respond_to do |format|
			if @artist.save
				format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
				format.json { render :show, status: :created, location: @artist }
			else
				format.html { render :new }
				format.json { render json: @artist.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /artists/1
	# PATCH/PUT /artists/1.json
	def update
		respond_to do |format|
			if @artist.update(artist_params)
				format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
				format.json { render :show, status: :ok, location: @artist }
			else
				format.html { render :edit }
				format.json { render json: @artist.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /artists/1
	# DELETE /artists/1.json
	def destroy
		@artist.destroy
		respond_to do |format|
			format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_artist
			@artist = Artist.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def artist_params
			params.require(:artist).permit(:name)
		end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @artists = Artist.all
    @songs = Song.all
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @tracks = Song.all.limit(5)
    @genres = Genre.all
    @songs = Song.all
  end

  def contact
  end

  def thanks
  	@song = Song.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @songs = Song.where('title iLike?', "%#{params[:q]}%").order(created_at: :desc)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :price, :artist, :image, :mp3, :genre_id)
    end

    def authenticate_admin
      current_user.try(:admin?)
    end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  def show
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/sonts_helper.rb
module SontsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/genres/index.html.haml
%h1 Genres#index
%p Find me in app/views/genres/index.html.haml

app/views/genres/show.html.haml
%section
    .container
        .pt-5.pb-5
            %h1= @genre.name
            
            .row
                = render @genre.songs

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true, html: { multipart: true }) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, id: :song_title , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price, class: "form-label" %>
    <%= form.number_field :price, id: :song_price , class: "form-control" %>
  </div>


  <div class="form-group">
    <%= form.label :artist, class: "form-label" %>
    <%= form.text_field :artist, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :genre, class: "form-label" %>
    <%= form.collection_select :genre_id, Genre.order(:name), :id, :name, {} , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, id: :image %>
  </div>

  <div class="form-group">
    <%= form.label :mp3, class: "form-label" %>
    <%= form.file_field :mp3, id: :image %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/songs/_song.html.haml
.col-sm-3.col-6
    = link_to song do
        .card.bg-dark.text-white
            = image_tag(song.image.url, class: "card-img")
            .card-img-overlay
                %h5.card-title= song.title
                %p.card-text= song.artist

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <% @songs.each do |song| %>

        <div class="col-sm-3">
          <%= link_to song do %>
          <div class="card bg-dark text-white">
            <%= image_tag(song.image.url, class: "card-img")%>
              <div class="card-img-overlay">
                <h5 class="card-title"><%= song.title %></h5>
                <!-- <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text">Last updated 3 mins ago</p> -->
              </div>
            </div>
          <% end %>
        </div>

    <% end %>
  </div>
</div>

app/views/songs/new.html.erb
<div class="container">
	<h1 class="text-center py-3">
		Add new song
	</h1>
	<div class="row justify-content-center">
		<div class="col-sm-4">
			<%= render 'form', song: @song %>

			<%= link_to 'Back', songs_path %>
		</div>
	</div>
</div>

app/views/songs/show.html.erb
<div class="container pt-5 pb-5">
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-6">
          <%= image_tag(@song.image.url, class: "card-img-top")%>
        </div>
        <div class="col-sm-6">
            <div class="pt-3">
              <h1><strong><%= @song.artist %><strong> - <%= @song.title %></h1>

              <p>
                <span class="badge badge-warning"><%= link_to @song.genre.name, @song.genre %></span>
              </p>


              
              <!-- <a href="" class="btn btn-dark" data-toggle="">Download for GHS1</a> -->
              <div class="btn btn-dark" data-toggle="modal" data-target="#exampleModal">
                Buy for GHS1
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-warning">
        <h5 class="modal-title" id="exampleModalLabel">Make Payment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <input type="text" id="phoneNumber" class="form-control" placeholder="Phone number ... ">
          </div>
          <div class="form-group">
            <select class="form-control" name="network">
              <option value="mtn">Mtn</option>
              <option value="airtel">Airtel</option>
              <option value="tigo">Tigo</option>
            </select>

          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-dark" id="paybtn">Pay</button>
      </div>
    </div>
  </div>
  <script type="text/javascript">

    $(document).ready(function(){
        var paybtn = $("#paybtn");

        
        

        paybtn.click(function(){
          var numberBox = $("#phoneNumber");
          var number = numberBox.val();
          var network = $("select[name='network']").val();
          var option = "";
          console.log(number);
          if (network == "mtn") {
            option = "rmtt";
          } else if (network == "airtel") {
            option = "ratt";
          } else if (network == "tigo"){
            option = "rttt";
          }

          console.log(option);
          var requestPayload = {
            "price": <%= @song.price.to_i %>,
            "network": network,
            "recipient_number": "0275338407",
            "sender": number,
            "option": option,
            "apikey": "d1be6bb296516815da89acd2bdfa4f25085d575d"
          }

          var payload = JSON.stringify(requestPayload);

          var xhr = new XMLHttpRequest();
          xhr.open("POST", 'https://client.teamcyst.com/api_call.php', true);

          //Send the proper header information along with the request
          xhr.setRequestHeader("Content-type", "application/json");

          xhr.onreadystatechange = function() {
            //Call a function when the state changes.
              if(xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200) {
                  // Request finished. Do processing here.
                  console.log(this.responseText);
                  location.href = "/thankyou/<%= @song.id %>";
              }
          }
          console.log(payload);
          //Replace requestPayload with the payload you would be sending
          xhr.send(payload);
        });

    });



</script>
</div>