config/routes.rb
Rails.application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'genres/index'

  get 'genres/show'

  get '/thankyou', to: 'pages#thanks'
  
  resources :artists
  get 'dashboards/show'

  resources :thanks, only: :show
  devise_for :users, controllers: {:registrations => 'users/registrations'}
  resources :songs
  resources :genres
  get 'pages/index'

  get 'thankyou/:id', to: "thanks#show"

  get 'pages/contact'

  get :search, controller: :searches


  get "/dashboard", to: "dashboards#show"
  root "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    # has_many :songs, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :genre

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  has_attached_file :mp3
  validates_attachment :mp3,content_type: { content_type: ["audio/mpeg", "audio/mp3"] },
                      file_name: { matches: [/mp3\Z/] }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @tracks = Song.all.limit(5)
    @genres = Genre.all
    @songs = Song.all
  end

  def contact
  end

  def thanks
  	@song = Song.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :price, :artist, :image, :mp3, :genre_id)
    end

    def authenticate_admin
      current_user.try(:admin?)
    end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  def show
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/sonts_helper.rb
module SontsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning navbar-fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/"><strong>AliveMusic</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-align-right"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_with( url: search_path, method: :get, local: true, class: 'form-inline my-2 my-lg-0') do |f| %>
        <%= f.text_field :q, class: "form-control", placeholder: "Search products and stores" %>
        <%= f.submit "Search", class: 'btn btn-dark my-2 my-sm-0'%>
      <% end %>
      
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <% if current_user %>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_user.email %>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right">
                    <%= link_to "New music", new_song_path, class: "dropdown-item" %>
      							<div class="dropdown-divider"></div>

      							<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

      						</div>
              </li>
              <% if current_user.admin? %>
                <li class="nav-item">
                  <%= link_to "View admin panel", dashboard_path, class: "nav-link"%>
                </li>
              <% end %>

            <% elsif current_artist %>
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_artist.email %>
                </a>

                <div class="dropdown-menu dropdown-menu-right">




                <div class="dropdown-divider"></div>

                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login/Sign up", new_user_registration_path, class: "btn btn-dark" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/fonts/open-iconic.ttf">
  </head>

  <body class="bg-white">
    <%= render "layouts/header" %>
    <div class="">
      <%= yield %>
    </div>

  <script type="text/javascript">
    $(document).on('turbolinks:load', function(){
      $('.carousel').carousel({
          interval: 2000
      });
    });
  </script>

  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<div class="jumbotron bg-white hero">

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @tracks.each.with_index(0) do |song, index| %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% @tracks.each.with_index(0) do |song, index| %>
      <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
        <%= link_to song.image.url do %>
          <%= image_tag(song.image.url, class: 'd-block w-100 img-fluid') %>
        <% end %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>


<div class="container">
  <div class='trending_section mb-5'>
    <h1 class='text-center'>Latest releases</h1>
    <div class='row'>
      <% @songs.each do |song| %>
        <div class='col-sm-3 col-6'>
          <%= link_to song do %>
            <div class='card bg-dark text-white'>
                <%= image_tag(song.image.url, class: "card-img") %>
                <div class='card-img-overlay'>
                  <h5 class='card-title'><%= song.title %></h5>
                  <p class='card-text'><%= song.artist %></p>
                </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='genre_section'>
    <h1 class='text-center'>Genres</h1>
    <div class='row'>
      <% @genres.each do |g| %>
        <div class='col-sm-3 col-6'>
          <div class='card'>
            <div class='card-body' style="background-image: url('<%= g.songs.last.image.url %>')">
              <h3><%= link_to g.name, g %></h3>
              <p><%= g.songs.last.title %></p>
              <p><%= link_to "See more", g %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

 

app/views/pages/thanks.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<h1 class="text-center">Thank You</h1>

				<audio controls>
					<source src="<%= @song.mp3.url%>" type="audio/mp3">
					<source src="<%= @song.mp3.url%>" type="audio/ogg">
              </audio>
              <br>
		</div>
	</div>
</div>